// Stub generated by compact compile - replace with real output after running: pnpm compact
export const ledger = {};
export const pureCircuits = {};
export const witnesses = {};
export const Contract = class {};
export const contractAddress = '';
